In [10]:
import numpy as np
import time

In [7]:
###  Creating array from list

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1D Array :", arr_1d)

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("2D Array :", arr_2d)

1D Array : [ 1  2  3  4  5  6  7  8  9 10]
2D Array : [[1 2 3 4]
 [5 6 7 8]]


In [11]:
### List vs numpy array

py_list = [1,2,3]
print("Python list multiplication :", py_list * 2)

np_array = np.array([1,2,3])
print("Numpy array multiplication :", np_array * 2)

start = time.time()

py_list = [i*2 for i in range(100000)]
print("\n List operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(100000) * 2
print("\n array operation time : ", time.time() - start)


Python list multiplication : [1, 2, 3, 1, 2, 3]
Numpy array multiplication : [2 4 6]

 List operation time :  0.005156993865966797

 array operation time :  0.0035593509674072266


In [18]:
### Arrays from scratch

zeros = np.zeros((3,4))
print("Zeros Array : \n", zeros)

ones = np.ones((3,4))
print("Ones Array : \n", ones)

full = np.full((3,4), 7)
print("Full Array : \n", full)


random = np.random.random((3,4))
print("Random Array : \n", random)

sequence = np.arange(0, 10, 2)
print("Sequence Array : \n", sequence)

Zeros Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array : 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Random Array : 
 [[0.41598023 0.72002075 0.54961893 0.54297254]
 [0.93775704 0.03909721 0.14353277 0.47448064]
 [0.53269939 0.18251299 0.69722153 0.98235676]]
Sequence Array : 
 [0 2 4 6 8]


In [20]:
### Vector, Matrices and tensor

vector = np.array([1,2,3])
print("Vector Array : \n", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix Array : \n", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("Tensor Array : \n", tensor)

Vector Array : 
 [1 2 3]
Matrix Array : 
 [[1 2 3]
 [4 5 6]]
Tensor Array : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
### Array Properties

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Shap", arr.shape)
print("Size", arr.size)
print("DType", arr.dtype)
print("Dimension", arr.ndim)

Shap (3, 3)
Size 9
DType int64
Dimension 2


In [23]:
arr = np.arange(12)
print("Original Array : \n", arr)

reshaped = arr.reshape(3,4)
print("Reshaped Array : \n", reshaped)

flattened = reshaped.flatten()
print("Flattened Array : \n", flattened)

raveled = reshaped.ravel()
print("Raveled Array : \n", raveled)

transpose = reshaped.T
print("Transposed Array : \n", transpose)

Original Array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
