### Advance Operation with Business Example

In [8]:
import numpy as np

sales_data = np.array([[1, 150000, 180000, 220000, 250000],
                       [2, 120000, 140000, 160000, 190000],
                       [3, 200000, 230000, 260000, 300000],
                       [4, 180000, 210000, 240000, 270000],
                       [5, 160000, 185000, 205000, 230000]])

print("\n Sale Data Shape", sales_data.shape)
# print("\n Skip the id from data:\n", sales_data[:, 1:])
print("\n Get first 3 records data:\n", sales_data[:3])


 Sale Data Shape (5, 5)

 Skip the id from data:
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]

 Get first 3 records data:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
