In [1]:
import numpy as np

In [4]:
### Array Operations

array = np.array([1,2,3,4,5,6,7,8,9])

print("Basic Slicing :", array[2:7])
print("With Step Slicing :", array[2:8:2])

Basic Slicing : [3 4 5 6 7]
With Step Slicing : [3 5 7]


In [8]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Target Specific Elements :", arr_2d[1, 2])
print("Entire Row :", arr_2d[1])
print("Entire Column :", arr_2d[:,1])

Target Specific Elements : 6
Entire Row : [4 5 6]
Entire Column : [2 5 8]


### Sorting


In [14]:
arr = np.array([2,1,3,6,5,4])
print("Sorted Array :", np.sort(arr))

arr_2d = np.array([[3,1],
                   [1,2],
                   [2,3]])

print("2D Array Sorted : \n", np.sort(arr_2d, axis=0))

Sorted Array : [1 2 3 4 5 6]
2D Array Sorted : 
 [[1 1]
 [2 2]
 [3 3]]


### Filters


In [15]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
even_arr = arr[arr % 2 == 0]
print("Even Array :", even_arr)

Even Array : [ 2  4  6  8 10]


## Mask

In [17]:
mask = arr > 5
print("Numbers Grater then 5 : ", arr[mask])

Numbers Grater then 5 :  [ 6  7  8  9 10]


### Fancy Indexing & np.where

In [19]:
indices = [0,2,4]
print(arr[indices])

where_results = np.where(arr > 5)
print(arr[where_results])

[1 3 5]
[ 6  7  8  9 10]


### Adding & Removing data

In [23]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate([arr1, arr2])
print("Combined Array :", combined)

Combined Array : [1 2 3 4 5 6]


### Array Compatibility

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Compatibility Array : ", a.shape == b.shape)

Compatibility Array :  True


In [27]:
### For Adding new row & Column in the array

original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])
arr_with_row = np.vstack((original, new_row))
print("New Array With Row : \n", arr_with_row)

new_col = np.array([[7], [8]])
arr_with_col = np.hstack((original, new_col))
print("New Array With Column : \n", arr_with_col)

New Array With Row : 
 [[1 2]
 [3 4]
 [5 6]]
New Array With Column : 
 [[1 2 7]
 [3 4 8]]


In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
deleted = np.delete(arr, 2)
print("Deleted Array : \n", deleted)

Deleted Array : 
 [ 1  2  4  5  6  7  8  9 10]
